import { Trip, Participant, Booking, Expense, Payment, LedgerEvent, Vendor, RefundEvent } from './types';

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'v1',
    tripId: 'trip-goa-2026',
    name: 'Taj Host Villas Goa',
    category: 'lodging',
    contactPhone: '+91 98230 11223',
    email: 'reservations@tajvillasgoa.com',
    website: 'https://tajvillasgoa.com',
    rating: 4.8,
    totalBookingsCount: 1,
    totalSpent: 68000,
  },
  {
    id: 'v2',
    tripId: 'trip-goa-2026',
    name: 'Goa Wheels Self-Drive',
    category: 'transport',
    contactPhone: '+91 98112 44556',
    email: 'rentals@goawheels.in',
    website: 'https://goawheels.in',
    rating: 4.6,
    totalBookingsCount: 1,
    totalSpent: 21500,
  },
  {
    id: 'v3',
    tripId: 'trip-goa-2026',
    name: 'Mandovi Luxury Marine',
    category: 'activity',
    contactPhone: '+91 97654 32100',
    email: 'charters@mandovimarine.in',
    website: 'https://mandovimarine.in',
    rating: 4.9,
    totalBookingsCount: 1,
    totalSpent: 30000,
  },
  {
    id: 'v4',
    tripId: 'trip-goa-2026',
    name: 'Thalassa Beach Restaurant',
    category: 'food',
    contactPhone: '+91 98221 88776',
    email: 'bookings@thalassagoa.com',
    rating: 4.7,
    totalBookingsCount: 1,
    totalSpent: 19800,
  },
  {
    id: 'v5',
    tripId: 'trip-goa-2026',
    name: 'Western Ghats Treks',
    category: 'activity',
    contactPhone: '+91 94481 99001',
    email: 'info@westernghatstreks.com',
    rating: 4.5,
    totalBookingsCount: 1,
    totalSpent: 8500,
  },
];

export const INITIAL_REFUNDS: RefundEvent[] = [];

export const INITIAL_TRIP: Trip = {
  id: 'trip-goa-2026',
  title: 'Goa & Gokarna Sunsets 2026',
  destination: 'Goa & Gokarna, India',
  baseCurrency: 'INR',
  startDate: '2026-11-10',
  endDate: '2026-11-18',
  budgetCeiling: 250000,
  inviteCode: 'GOA2026',
  organizerId: 'p1',
  createdAt: '2026-11-01T09:00:00Z',
};

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'p1',
    tripId: 'trip-goa-2026',
    name: 'Srushti Sharma',
    email: 'srushti@fareshare.in',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isOrganizer: true,
    status: 'active',
    upiId: 'srushti.sharma@okicici',
    weight: 1,
    roomTier: 'suite',
  },
  {
    id: 'p2',
    tripId: 'trip-goa-2026',
    name: 'Ananya Iyer',
    email: 'ananya@fareshare.in',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'ananya.iyer@upi',
    weight: 1,
    roomTier: 'standard',
  },
  {
    id: 'p3',
    tripId: 'trip-goa-2026',
    name: 'Rohan Mehta',
    email: 'rohan@fareshare.in',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'rohan.m@okhdfcbank',
    weight: 1,
    roomTier: 'standard',
  },
  {
    id: 'p4',
    tripId: 'trip-goa-2026',
    name: 'Priya Patel',
    email: 'priya@fareshare.in',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'priyapatel@paytm',
    weight: 1,
    roomTier: 'economy',
  },
  {
    id: 'p5',
    tripId: 'trip-goa-2026',
    name: 'Diya Verma',
    email: 'diya@fareshare.in',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'diya.v@ybl',
    weight: 0.8,
    roomTier: 'standard',
  },
  {
    id: 'p6',
    tripId: 'trip-goa-2026',
    name: 'Kabir Roy',
    email: 'kabir@fareshare.in',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    isOrganizer: false,
    status: 'active',
    upiId: 'kabir.roy@postbank',
    weight: 1,
    roomTier: 'suite',
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'b1',
    tripId: 'trip-goa-2026',
    category: 'lodging',
    title: 'Heritage Beach Villa & Private Pool (Vagator)',
    vendor: 'Taj Host Villas Goa',
    startTime: '2026-11-10T15:00:00Z',
    endTime: '2026-11-15T11:00:00Z',
    estimatedCost: 65000,
    actualCost: 68000,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
  },
  {
    id: 'b2',
    tripId: 'trip-goa-2026',
    category: 'transport',
    title: 'Self-Drive SUV Rentals & Airport Transfers',
    vendor: 'Goa Wheels Self-Drive',
    startTime: '2026-11-10T12:00:00Z',
    endTime: '2026-11-18T16:00:00Z',
    estimatedCost: 22000,
    actualCost: 21500,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p4', 'p5', 'p6'],
  },
  {
    id: 'b3',
    tripId: 'trip-goa-2026',
    category: 'activity',
    title: 'Private Sunset Yacht Charter & Scuba Diving',
    vendor: 'Mandovi Luxury Marine',
    startTime: '2026-11-12T15:30:00Z',
    endTime: '2026-11-12T19:00:00Z',
    estimatedCost: 28000,
    actualCost: 30000,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p6'],
  },
  {
    id: 'b4',
    tripId: 'trip-goa-2026',
    category: 'food',
    title: 'Seafood Barbecue & Cocktails at Thalassa',
    vendor: 'Thalassa Beach Restaurant',
    startTime: '2026-11-13T20:00:00Z',
    endTime: '2026-11-13T23:30:00Z',
    estimatedCost: 18000,
    actualCost: 19800,
    status: 'confirmed',
    participantIds: ['p1', 'p2', 'p3', 'p4', 'p6'],
  },
  {
    id: 'b5',
    tripId: 'trip-goa-2026',
    category: 'activity',
    title: 'Gokarna Beach Trek & Temple Cultural Tour',
    vendor: 'Western Ghats Treks',
    startTime: '2026-11-16T08:00:00Z',
    endTime: '2026-11-16T17:00:00Z',
    estimatedCost: 9000,
    actualCost: 8500,
    status: 'confirmed',
    participantIds: ['p2', 'p3', 'p4', 'p5'],
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'e1',
    tripId: 'trip-goa-2026',
    bookingId: 'b1',
    title: 'Vagator Heritage Villa Deposit & Booking',
    totalAmount: 68000,
    currency: 'INR',
    splitMethod: 'room_tier',
    paidById: 'p1',
    category: 'lodging',
    createdAt: '2026-11-10T16:00:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
    receiptName: 'Taj_Villa_Vagator_TaxInvoice.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 15280 },
      { participantId: 'p2', amountOwed: 10920 },
      { participantId: 'p3', amountOwed: 10920 },
      { participantId: 'p4', amountOwed: 8730 },
      { participantId: 'p5', amountOwed: 6870 },
      { participantId: 'p6', amountOwed: 15280 },
    ],
  },
  {
    id: 'e2',
    tripId: 'trip-goa-2026',
    bookingId: 'b2',
    title: 'Self-Drive SUV Rentals & Fuel Fill-Up',
    totalAmount: 21500,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p6',
    category: 'transport',
    createdAt: '2026-11-11T09:00:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80',
    receiptName: 'GoaWheels_Invoice_21500.jpg',
    allocations: [
      { participantId: 'p1', amountOwed: 3583.33 },
      { participantId: 'p2', amountOwed: 3583.33 },
      { participantId: 'p3', amountOwed: 3583.33 },
      { participantId: 'p4', amountOwed: 3583.33 },
      { participantId: 'p5', amountOwed: 3583.33 },
      { participantId: 'p6', amountOwed: 3583.35 },
    ],
  },
  {
    id: 'e3',
    tripId: 'trip-goa-2026',
    bookingId: 'b3',
    title: 'Sunset Yacht Charter & Marine Gears',
    totalAmount: 30000,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p1',
    category: 'activity',
    createdAt: '2026-11-12T17:00:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    receiptName: 'Yacht_Charter_Goa_Receipt.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 7500 },
      { participantId: 'p2', amountOwed: 7500 },
      { participantId: 'p3', amountOwed: 7500 },
      { participantId: 'p6', amountOwed: 7500 },
    ],
  },
  {
    id: 'e4',
    tripId: 'trip-goa-2026',
    bookingId: 'b4',
    title: 'Thalassa Seafood Feast & Wine Pairing',
    totalAmount: 19800,
    currency: 'INR',
    splitMethod: 'organizer_subsidy',
    paidById: 'p3',
    category: 'food',
    subsidyAmount: 4800,
    createdAt: '2026-11-13T22:30:00Z',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=80',
    receiptName: 'Thalassa_Bill_19800.png',
    allocations: [
      { participantId: 'p1', amountOwed: 3000 },
      { participantId: 'p2', amountOwed: 3000 },
      { participantId: 'p3', amountOwed: 3000 },
      { participantId: 'p4', amountOwed: 3000 },
      { participantId: 'p6', amountOwed: 3000 },
    ],
  },
  {
    id: 'e5',
    tripId: 'trip-goa-2026',
    bookingId: 'b5',
    title: 'Gokarna Beach Trek & Guide Fee',
    totalAmount: 8500,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p2',
    category: 'activity',
    createdAt: '2026-11-16T14:00:00Z',
    allocations: [
      { participantId: 'p2', amountOwed: 2125 },
      { participantId: 'p3', amountOwed: 2125 },
      { participantId: 'p4', amountOwed: 2125 },
      { participantId: 'p5', amountOwed: 2125 },
    ],
  },
  {
    id: 'e6',
    tripId: 'trip-goa-2026',
    title: 'Airport Express Cabs & Intercity Highway Tolls',
    totalAmount: 4200,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p3',
    category: 'transport',
    createdAt: '2026-11-10T14:00:00Z',
    receiptName: 'GoaCabs_FastagReceipts.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 700 },
      { participantId: 'p2', amountOwed: 700 },
      { participantId: 'p3', amountOwed: 700 },
      { participantId: 'p4', amountOwed: 700 },
      { participantId: 'p5', amountOwed: 700 },
      { participantId: 'p6', amountOwed: 700 },
    ],
  },
  {
    id: 'e7',
    tripId: 'trip-goa-2026',
    title: "Fisherman's Wharf Goan Prawn Curry & Thali Lunch",
    totalAmount: 7200,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p4',
    category: 'food',
    createdAt: '2026-11-14T13:45:00Z',
    receiptName: 'FishermansWharf_Lunch_TaxInvoice.pdf',
    allocations: [
      { participantId: 'p1', amountOwed: 1200 },
      { participantId: 'p2', amountOwed: 1200 },
      { participantId: 'p3', amountOwed: 1200 },
      { participantId: 'p4', amountOwed: 1200 },
      { participantId: 'p5', amountOwed: 1200 },
      { participantId: 'p6', amountOwed: 1200 },
    ],
  },
  {
    id: 'e8',
    tripId: 'trip-goa-2026',
    title: 'Curlies Beach Shack Live Music & Sundowner Drinks',
    totalAmount: 9600,
    currency: 'INR',
    splitMethod: 'equal',
    paidById: 'p5',
    category: 'activity',
    createdAt: '2026-11-14T23:30:00Z',
    receiptName: 'Curlies_Anjuna_Receipt.jpg',
    allocations: [
      { participantId: 'p1', amountOwed: 1600 },
      { participantId: 'p2', amountOwed: 1600 },
      { participantId: 'p3', amountOwed: 1600 },
      { participantId: 'p4', amountOwed: 1600 },
      { participantId: 'p5', amountOwed: 1600 },
      { participantId: 'p6', amountOwed: 1600 },
    ],
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay1',
    tripId: 'trip-goa-2026',
    payerId: 'p4',
    payeeId: 'p2',
    amount: 2500,
    note: 'UPI Payment via Google Pay (Ref: 4329019283)',
    createdAt: '2026-11-15T10:00:00Z',
  },
];

export const INITIAL_EVENTS: LedgerEvent[] = [
  {
    id: 'evt-1',
    tripId: 'trip-goa-2026',
    eventType: 'TRIP_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-01T09:00:00Z',
    description: 'Trip "Goa & Gokarna Sunsets 2026" created with Invite Code GOA2026 and budget ceiling ₹1,50,000.',
    payload: { budget: 150000, inviteCode: 'GOA2026' },
    sequenceNum: 1,
  },
  {
    id: 'evt-2',
    tripId: 'trip-goa-2026',
    eventType: 'PARTICIPANT_ADDED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-02T14:30:00Z',
    description: 'Added Ananya, Rohan, Priya, Diya, and Kabir to Goa trip roster with UPI IDs attached.',
    payload: { count: 5, roster: ['Ananya Iyer', 'Rohan Mehta', 'Priya Patel', 'Diya Verma', 'Kabir Roy'] },
    sequenceNum: 2,
  },
  {
    id: 'evt-3',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-05T11:00:00Z',
    description: 'Created booking "Heritage Beach Villa & Private Pool (Vagator)" with Taj Host Villas Goa (₹68,000.00).',
    payload: { bookingId: 'b1', vendor: 'Taj Host Villas Goa', amount: 68000, category: 'lodging' },
    sequenceNum: 3,
  },
  {
    id: 'evt-4',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-10T16:00:00Z',
    description: 'Logged expense "Vagator Heritage Villa Deposit & Booking" (₹68,000.00) using Room-Tier split with verified receipt proof attached.',
    payload: { expenseId: 'e1', amount: 68000, splitMethod: 'room_tier' },
    sequenceNum: 4,
  },
  {
    id: 'evt-5',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-10T17:30:00Z',
    description: 'Created booking "Self-Drive SUV Rentals & Airport Transfers" with Goa Wheels Self-Drive (₹21,500.00).',
    payload: { bookingId: 'b2', vendor: 'Goa Wheels Self-Drive', amount: 21500, category: 'transport' },
    sequenceNum: 5,
  },
  {
    id: 'evt-6',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p6',
    actorName: 'Kabir Roy',
    timestamp: '2026-11-11T09:00:00Z',
    description: 'Logged expense "Self-Drive SUV Rentals & Fuel Fill-Up" (₹21,500.00) via Equal split across all 6 members.',
    payload: { expenseId: 'e2', amount: 21500, splitMethod: 'equal' },
    sequenceNum: 6,
  },
  {
    id: 'evt-7',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-12T10:00:00Z',
    description: 'Created booking "Private Sunset Yacht Charter & Scuba Diving" with Mandovi Luxury Marine (₹30,000.00).',
    payload: { bookingId: 'b3', vendor: 'Mandovi Luxury Marine', amount: 30000, category: 'activity' },
    sequenceNum: 7,
  },
  {
    id: 'evt-8',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-12T17:00:00Z',
    description: 'Logged expense "Sunset Yacht Charter & Marine Gears" (₹30,000.00) via Equal split (4 participants).',
    payload: { expenseId: 'e3', amount: 30000, splitMethod: 'equal' },
    sequenceNum: 8,
  },
  {
    id: 'evt-9',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-13T14:00:00Z',
    description: 'Created booking "Seafood Barbecue & Cocktails at Thalassa" with Thalassa Beach Restaurant (₹19,800.00).',
    payload: { bookingId: 'b4', vendor: 'Thalassa Beach Restaurant', amount: 19800, category: 'food' },
    sequenceNum: 9,
  },
  {
    id: 'evt-10',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p3',
    actorName: 'Rohan Mehta',
    timestamp: '2026-11-13T22:30:00Z',
    description: 'Logged expense "Thalassa Seafood Feast & Wine Pairing" (₹19,800.00) with ₹4,800 Organizer Subsidy.',
    payload: { expenseId: 'e4', amount: 19800, subsidy: 4800, splitMethod: 'organizer_subsidy' },
    sequenceNum: 10,
  },
  {
    id: 'evt-11',
    tripId: 'trip-goa-2026',
    eventType: 'BOOKING_CREATED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-15T09:00:00Z',
    description: 'Created booking "Gokarna Beach Trek & Temple Cultural Tour" with Western Ghats Treks (₹8,500.00).',
    payload: { bookingId: 'b5', vendor: 'Western Ghats Treks', amount: 8500, category: 'activity' },
    sequenceNum: 11,
  },
  {
    id: 'evt-12',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p2',
    actorName: 'Ananya Iyer',
    timestamp: '2026-11-16T14:00:00Z',
    description: 'Logged expense "Gokarna Beach Trek & Guide Fee" (₹8,500.00) via Equal split.',
    payload: { expenseId: 'e5', amount: 8500, splitMethod: 'equal' },
    sequenceNum: 12,
  },
  {
    id: 'evt-13',
    tripId: 'trip-goa-2026',
    eventType: 'PAYMENT_RECORDED',
    actorId: 'p4',
    actorName: 'Priya Patel',
    timestamp: '2026-11-15T10:00:00Z',
    description: 'Recorded UPI settlement payment of ₹2,500.00 from Priya Patel to Ananya Iyer (Ref: 4329019283).',
    payload: { paymentId: 'pay1', amount: 2500, payer: 'Priya Patel', payee: 'Ananya Iyer' },
    sequenceNum: 13,
  },
  {
    id: 'evt-14',
    tripId: 'trip-goa-2026',
    eventType: 'EXPENSE_LOGGED',
    actorId: 'p1',
    actorName: 'Srushti Sharma',
    timestamp: '2026-11-17T11:45:00Z',
    description: 'Logged expense "Cab to the Airport" (₹5,000.00) via equal split rule.',
    payload: { title: 'Cab to the Airport', amount: 5000, splitMethod: 'equal' },
    sequenceNum: 14,
  },
];
